[package]
name = "murderous-artists"
version = "0.1.0"
authors = ["Oliver Sõro <oliver.s6ro@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
